#! /bin/sh
# Contributed by Pi Zhenwei <p_ace@126.com>, 2016

DEFAULT_MALLOC_TRACE=$HOME/catchleak

record()
{
  shift
  #echo " in record : $# : $@"
  if [ $# -le 0 ]; then
    echo "$0: missing arguments" >&2
    exit 1
  fi

  if [ -z "$MALLOC_TRACE" ]; then
    echo "MALLOC_TRACE is emtpy, use default : $DEFAULT_MALLOC_TRACE"
    MALLOC_TRACE=$DEFAULT_MALLOC_TRACE
  fi

  mkdir -p $MALLOC_TRACE
  LD_PRELOAD=${LD_PRELOAD:+${LD_PRELOAD}:}/lib/catchleak.so
  export MALLOC_TRACE
  export LD_PRELOAD
  echo 'recording ...'
  (exec 3>&2 2>/dev/null
  #echo "LD_PRELOAD : $LD_PRELOAD"; \
  $@ 2>&3 3>&-)
}

report()
{
  if [ -z "$MALLOC_TRACE" ]; then
    MALLOC_TRACE=$DEFAULT_MALLOC_TRACE
    echo "MALLOC_TRACE is : $MALLOC_TRACE"
  fi

  for trace in `ls $MALLOC_TRACE | grep catchleak_mtrace`;
  do
	echo "----------------------$MALLOC_TRACE/$trace-------------------"
    mtrace $MALLOC_TRACE/$trace
  done
}

parse()
{
  case "$1" in
    --v | --ve | --ver | --vers | --versi | --versio | --version)
      echo 'catchleak 0.1'
      exit 0
      ;;
    --rec | --record)
      record "$@"
      exit 0
      ;;
    --rep | --report)
      report
      exit 0
      ;;
    --h | --he | --hel | --help | *)
      echo 'Usage: catchleak PROGRAM ARGS...'
      echo '  --help      print this help'
      echo '  --version   print version number'
      exit 0
      ;;
  esac
}

if test $# -eq 0; then
  echo "$0: missing arguments" >&2
  echo "Try \`$0 --help' for more information." >&2
  exit 1
fi

parse "$@"
exit 0
